WORKSHEETS:
    meta: Simulator
    block_sched: Block Schedule
    btc_price: BTC Projection
    fees: Fee Projection
    pools: Pools
    projects: Projects
    miners: Miners
    cooling: Cooling
    envs: Simulator
    minenv: Mining Environment
    proj_comp: Project Comparison
    proj_temp: __ProjectTemplate
TABLES:
    meta: MetaSumm
    miners: MinerDB
    cooling: CoolingProfiles
    pools: PoolProfiles
    projects: ProjectProfiles
    block_sched: BlockSchedule
    btc_price: BTCForecast
    btc_cagrs: D9
    fees: FeeForecast
    block_sched_inputs: B2:B3
    btc_price_inputs: B2:B5
    fees_inputs: B2:B5
BUTTONS:
    env: SimulateEnvButton
    proj: SimulateProjectsButton
    block_sched: ScheduleButton
    btc_price: BTCForecastButton
    fees: FeeForecastButton
CHECKLIST_CELLS:
    block_sched: B13
    btc_price: B14
    fees: B15
LOAD_CELLS:
    miners: L2
    pools: P2
    projects: B17
    envs: D13
